Registration upgrade
hgezim/zip-recipes pull request #51
Opened 2016-09-14 10:29 UTC by Noilleris

Registration upgraded, need to to discuss, need you to review.

2016-09-14 13:53 UTC, hgezim commented
- [ ] Change submenu name to Settings
- [ ] Move Register up to top of submenu
- [ ] Registration should not be skippable in the settings
- [ ] Registration _should_ be skippable when user creates new post with recipe (should set cookie and come up again in a week ❤️)

2016-09-19 05:28 UTC, hgezim commented
There's an issue when a post is published. Error:
<img width="1804" alt="localhost_8080_wp-admin_post_php" src="https://cloud.githubusercontent.com/assets/124675/18623188/9a092660-7df7-11e6-8249-922822fc82f8.png">

2016-09-19 05:29 UTC, hgezim commented
Clicking `Settings` submenu doesn't take you to settings.

2016-09-20 15:00 UTC, hgezim commented on src/class.ziprecipes.php
> +                'registered_clear' => $registered_clear);
`registered_clear` and `register_url` is not being used in `settings.twig`

2016-09-20 15:03 UTC, hgezim commented on src/class.ziprecipes.php
>  		Util::print_view('create-update-recipe', array(
I think it's better to show `register.twig` here in the cases where we need to show it. This way we don't have to pollute `create-update-recipe` with too much registration stuff and we can remove macros from `register.twig`

2016-09-20 15:05 UTC, hgezim commented on src/views/create-update-recipe.twig
> +            $('#skip-button').click(function(e) {
We should only set cookie on backend and not two places. We're not using ajax much at all right now and this tiny thing doesn't help. In the future, I'd love to switch everything to AJAX and a good frontend JavaScript library!

2016-09-20 15:06 UTC, hgezim commented on src/views/create-update-recipe.twig
> +            {% if registration_required %}
Note comment above about how we shouldn't have to handle registration at all in this template.

2016-09-20 15:11 UTC, hgezim requested changes
Please make these changes I suggested. Reply to comments if they're not clear :)

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +            setcookie( 'skip-registration', 1, time()+60*60*24*7, '/' );
Make variable for expire time.

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +        $skip_reg=false;
`$skip_reg` should be `$skip_registration`. This short form doesn't help.

2016-09-20 15:11 UTC, hgezim commented on src/views/create-update-recipe.twig
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
Why not use WordPress's jQuery?

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +            if ($_POST['action'] === "zrdn-register") {
The block starting with `if ($_POST['action'] === "register")` won't be needed anymore in line 512, right?

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +            foreach ($_POST as $key => $val) {
Move this cleanup in `if ($_POST['action'] === "zrdn-register") {` because otherwise we do it for every request whether it's for us or not.

2016-09-20 15:11 UTC, hgezim commented on src/views/macros.twig
> +                $skip = jQuery("#skip-button");
`$skip` is not used.

2016-09-20 15:11 UTC, hgezim commented on src/views/create-update-recipe.twig
> +        {{ macros.scripts() }}
Using `macros` before it's imported.

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +        if (!$skip_reg) {
`$skip_reg` is going to always be false here so this check isn't needed.

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +    public static function preload_check_registered() {
I don't like how this breaks the post-> page rendering flow.
Why can't we set the submit method for the registration form to be a different url and handle the registration there?

This whole `exit()` and `die()` business doesn't feel right.

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +    public static function zrdn_registration() {
Add a comment before you declare `zrdn_registration` something like this:

```
/**
* Display registration form for Settings.
*/
```

2016-09-20 15:11 UTC, hgezim commented on src/class.ziprecipes.php
> +        $register_url = admin_url( 'admin.php?page=' . 'zrdn-register' );
Spacing is messed up here.

2016-09-21 11:28 UTC, Noilleris commented on src/views/create-update-recipe.twig
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
i should ask you.

2016-09-21 11:29 UTC, Noilleris commented on src/views/create-update-recipe.twig
> +            $('#skip-button').click(function(e) {
need to discuss

2016-09-25 15:42 UTC, hgezim commented on src/class.ziprecipes.php
> +            foreach ($_POST as $key => $val) {
Fix this.

2016-09-25 15:43 UTC, hgezim commented on src/class.ziprecipes.php
> +            if ($_POST['action'] === "zrdn-register") {
??

2016-09-25 15:43 UTC, hgezim commented on src/class.ziprecipes.php
> +            setcookie( 'skip-registration', 1, time()+60*60*24*7, '/' );
Fix this.

2016-09-25 15:43 UTC, hgezim commented on src/class.ziprecipes.php
> +    public static function zrdn_registration() {
Fix this

2016-09-25 15:44 UTC, hgezim commented on src/class.ziprecipes.php
> +        $register_url = admin_url( 'admin.php?page=' . 'zrdn-register' );
Fix this.

2016-09-25 15:44 UTC, hgezim commented on src/class.ziprecipes.php
> +                'registered_clear' => $registered_clear);
Is this true? Fix please, if so.

2016-09-25 15:44 UTC, hgezim commented on src/class.ziprecipes.php
> +        if (!$skip_reg) {
Fix this.

2016-09-25 15:45 UTC, hgezim commented on src/views/create-update-recipe.twig
> +        {{ macros.scripts() }}
Fix this.

2016-09-25 15:45 UTC, hgezim commented on src/views/macros.twig
> +                $skip = jQuery("#skip-button");
Fix this.

2016-09-25 15:45 UTC, hgezim reviewed
Fix all the stuff I mentioned today, only.

2016-09-25 15:46 UTC, hgezim commented
Also get rid of non-registration changes here like `__shortcode` crap.

2016-09-25 15:47 UTC, hgezim commented
..and `prettyfy_time` crap

2016-09-26 05:13 UTC, Noilleris commented on src/class.ziprecipes.php
> +            foreach ($_POST as $key => $val) {
Fixed, check comment above fuction.

2016-09-26 05:15 UTC, Noilleris commented on src/class.ziprecipes.php
> +            if ($_POST['action'] === "zrdn-register") {
Theis code is removed. So we need registration snippet on line 512.

2016-09-26 05:22 UTC, Noilleris commented on src/class.ziprecipes.php
> +            setcookie( 'skip-registration', 1, time()+60*60*24*7, '/' );
fixed

2016-09-26 05:22 UTC, Noilleris commented on src/class.ziprecipes.php
> +                'registered_clear' => $registered_clear);
It is fine.

2016-09-26 05:23 UTC, Noilleris commented on src/class.ziprecipes.php
> +        if (!$skip_reg) {
This is not exists anymore.

2016-09-26 05:23 UTC, Noilleris commented on src/views/create-update-recipe.twig
> +        {{ macros.scripts() }}
done

2016-09-26 05:26 UTC, Noilleris commented on src/class.ziprecipes.php
> +        $register_url = admin_url( 'admin.php?page=' . 'zrdn-register' );
fixed

2016-09-26 05:27 UTC, Noilleris commented on src/class.ziprecipes.php
> +    public static function zrdn_registration() {
fixed

2016-09-28 04:12 UTC, hgezim commented
Merged in #55

2016-09-28 04:12 UTC, closed without merging