Shortcodes
hgezim/zip-recipes pull request #53
Opened 2016-09-18 17:28 UTC by Noilleris

Here is 1 string commit;)

I've added line of code to init shortcodes facade.
I guess in future we should move shortcodes facade to main plugin.

2016-09-20 15:17 UTC, hgezim commented on src/class.ziprecipes.php
> +        $shortcodes = new __shortcode();
Where's `__shortcode` required or defined?

2016-09-20 15:17 UTC, hgezim commented on src/class.ziprecipes.php
> +        if (isset($_POST['page']) and strpos($_POST['page'], 'zrdn-') !== false) {
Registration changes should not be in this branch.

2016-09-20 15:48 UTC, hgezim requested changes

2016-09-21 11:50 UTC, Noilleris commented on src/class.ziprecipes.php
> +        $shortcodes = new __shortcode();
nowhere. and i do not quite understand why it so. mybe it is because of namespace.
need to discuss

2016-09-26 06:54 UTC, Noilleris commented on src/class.ziprecipes.php
> +        $shortcodes = new __shortcode();
fixed

2016-09-28 04:12 UTC, hgezim commented
Merged in #55

2016-09-28 04:12 UTC, closed without merging